# alb variables
variable "project-name" {}
variable "environment" {}
variable "alb_security_group_id" {}
variable "public_subnet_az1_id" {}
variable "public_subnet_az2_id" {}
variable "target_type" {}
variable "vpc.id" {}
variable "certificate_arn" {}
